/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyWordsRouteImport } from './routes/my-words'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialIndexRouteImport } from './routes/material/index'
import { Route as MaterialSlugIndexRouteImport } from './routes/material/$slug/index'
import { Route as MaterialSlugWordPatternsRouteImport } from './routes/material/$slug/word-patterns'
import { Route as MaterialSlugWordFormationRouteImport } from './routes/material/$slug/word-formation'
import { Route as MaterialSlugVocabularyRouteImport } from './routes/material/$slug/vocabulary'
import { Route as MaterialSlugQuizRouteImport } from './routes/material/$slug/quiz'
import { Route as MaterialSlugPrepositionalPhrasesRouteImport } from './routes/material/$slug/prepositional-phrases'
import { Route as MaterialSlugPhrasalVerbsRouteImport } from './routes/material/$slug/phrasal-verbs'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWordsRoute = MyWordsRouteImport.update({
  id: '/my-words',
  path: '/my-words',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIndexRoute = MaterialIndexRouteImport.update({
  id: '/material/',
  path: '/material/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugIndexRoute = MaterialSlugIndexRouteImport.update({
  id: '/material/$slug/',
  path: '/material/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugWordPatternsRoute =
  MaterialSlugWordPatternsRouteImport.update({
    id: '/material/$slug/word-patterns',
    path: '/material/$slug/word-patterns',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaterialSlugWordFormationRoute =
  MaterialSlugWordFormationRouteImport.update({
    id: '/material/$slug/word-formation',
    path: '/material/$slug/word-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaterialSlugVocabularyRoute = MaterialSlugVocabularyRouteImport.update({
  id: '/material/$slug/vocabulary',
  path: '/material/$slug/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugQuizRoute = MaterialSlugQuizRouteImport.update({
  id: '/material/$slug/quiz',
  path: '/material/$slug/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugPrepositionalPhrasesRoute =
  MaterialSlugPrepositionalPhrasesRouteImport.update({
    id: '/material/$slug/prepositional-phrases',
    path: '/material/$slug/prepositional-phrases',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaterialSlugPhrasalVerbsRoute =
  MaterialSlugPhrasalVerbsRouteImport.update({
    id: '/material/$slug/phrasal-verbs',
    path: '/material/$slug/phrasal-verbs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-words': typeof MyWordsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/material/': typeof MaterialIndexRoute
  '/material/$slug/phrasal-verbs': typeof MaterialSlugPhrasalVerbsRoute
  '/material/$slug/prepositional-phrases': typeof MaterialSlugPrepositionalPhrasesRoute
  '/material/$slug/quiz': typeof MaterialSlugQuizRoute
  '/material/$slug/vocabulary': typeof MaterialSlugVocabularyRoute
  '/material/$slug/word-formation': typeof MaterialSlugWordFormationRoute
  '/material/$slug/word-patterns': typeof MaterialSlugWordPatternsRoute
  '/material/$slug/': typeof MaterialSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-words': typeof MyWordsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/material': typeof MaterialIndexRoute
  '/material/$slug/phrasal-verbs': typeof MaterialSlugPhrasalVerbsRoute
  '/material/$slug/prepositional-phrases': typeof MaterialSlugPrepositionalPhrasesRoute
  '/material/$slug/quiz': typeof MaterialSlugQuizRoute
  '/material/$slug/vocabulary': typeof MaterialSlugVocabularyRoute
  '/material/$slug/word-formation': typeof MaterialSlugWordFormationRoute
  '/material/$slug/word-patterns': typeof MaterialSlugWordPatternsRoute
  '/material/$slug': typeof MaterialSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-words': typeof MyWordsRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/material/': typeof MaterialIndexRoute
  '/material/$slug/phrasal-verbs': typeof MaterialSlugPhrasalVerbsRoute
  '/material/$slug/prepositional-phrases': typeof MaterialSlugPrepositionalPhrasesRoute
  '/material/$slug/quiz': typeof MaterialSlugQuizRoute
  '/material/$slug/vocabulary': typeof MaterialSlugVocabularyRoute
  '/material/$slug/word-formation': typeof MaterialSlugWordFormationRoute
  '/material/$slug/word-patterns': typeof MaterialSlugWordPatternsRoute
  '/material/$slug/': typeof MaterialSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-words'
    | '/profile'
    | '/quiz'
    | '/material/'
    | '/material/$slug/phrasal-verbs'
    | '/material/$slug/prepositional-phrases'
    | '/material/$slug/quiz'
    | '/material/$slug/vocabulary'
    | '/material/$slug/word-formation'
    | '/material/$slug/word-patterns'
    | '/material/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-words'
    | '/profile'
    | '/quiz'
    | '/material'
    | '/material/$slug/phrasal-verbs'
    | '/material/$slug/prepositional-phrases'
    | '/material/$slug/quiz'
    | '/material/$slug/vocabulary'
    | '/material/$slug/word-formation'
    | '/material/$slug/word-patterns'
    | '/material/$slug'
  id:
    | '__root__'
    | '/'
    | '/my-words'
    | '/profile'
    | '/quiz'
    | '/material/'
    | '/material/$slug/phrasal-verbs'
    | '/material/$slug/prepositional-phrases'
    | '/material/$slug/quiz'
    | '/material/$slug/vocabulary'
    | '/material/$slug/word-formation'
    | '/material/$slug/word-patterns'
    | '/material/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyWordsRoute: typeof MyWordsRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  MaterialIndexRoute: typeof MaterialIndexRoute
  MaterialSlugPhrasalVerbsRoute: typeof MaterialSlugPhrasalVerbsRoute
  MaterialSlugPrepositionalPhrasesRoute: typeof MaterialSlugPrepositionalPhrasesRoute
  MaterialSlugQuizRoute: typeof MaterialSlugQuizRoute
  MaterialSlugVocabularyRoute: typeof MaterialSlugVocabularyRoute
  MaterialSlugWordFormationRoute: typeof MaterialSlugWordFormationRoute
  MaterialSlugWordPatternsRoute: typeof MaterialSlugWordPatternsRoute
  MaterialSlugIndexRoute: typeof MaterialSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-words': {
      id: '/my-words'
      path: '/my-words'
      fullPath: '/my-words'
      preLoaderRoute: typeof MyWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/': {
      id: '/material/'
      path: '/material'
      fullPath: '/material/'
      preLoaderRoute: typeof MaterialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/': {
      id: '/material/$slug/'
      path: '/material/$slug'
      fullPath: '/material/$slug/'
      preLoaderRoute: typeof MaterialSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/word-patterns': {
      id: '/material/$slug/word-patterns'
      path: '/material/$slug/word-patterns'
      fullPath: '/material/$slug/word-patterns'
      preLoaderRoute: typeof MaterialSlugWordPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/word-formation': {
      id: '/material/$slug/word-formation'
      path: '/material/$slug/word-formation'
      fullPath: '/material/$slug/word-formation'
      preLoaderRoute: typeof MaterialSlugWordFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/vocabulary': {
      id: '/material/$slug/vocabulary'
      path: '/material/$slug/vocabulary'
      fullPath: '/material/$slug/vocabulary'
      preLoaderRoute: typeof MaterialSlugVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/quiz': {
      id: '/material/$slug/quiz'
      path: '/material/$slug/quiz'
      fullPath: '/material/$slug/quiz'
      preLoaderRoute: typeof MaterialSlugQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/prepositional-phrases': {
      id: '/material/$slug/prepositional-phrases'
      path: '/material/$slug/prepositional-phrases'
      fullPath: '/material/$slug/prepositional-phrases'
      preLoaderRoute: typeof MaterialSlugPrepositionalPhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug/phrasal-verbs': {
      id: '/material/$slug/phrasal-verbs'
      path: '/material/$slug/phrasal-verbs'
      fullPath: '/material/$slug/phrasal-verbs'
      preLoaderRoute: typeof MaterialSlugPhrasalVerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyWordsRoute: MyWordsRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  MaterialIndexRoute: MaterialIndexRoute,
  MaterialSlugPhrasalVerbsRoute: MaterialSlugPhrasalVerbsRoute,
  MaterialSlugPrepositionalPhrasesRoute: MaterialSlugPrepositionalPhrasesRoute,
  MaterialSlugQuizRoute: MaterialSlugQuizRoute,
  MaterialSlugVocabularyRoute: MaterialSlugVocabularyRoute,
  MaterialSlugWordFormationRoute: MaterialSlugWordFormationRoute,
  MaterialSlugWordPatternsRoute: MaterialSlugWordPatternsRoute,
  MaterialSlugIndexRoute: MaterialSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
