-- Generated from apps/api/prisma/seed.ts's content arrays. See docs/vocab-app-plan.md.

-- Learning and Doing
insert into public.discourses (slug, title, description, "order", coming_soon) values ('learning-and-doing', 'Learning and Doing', 'Vocabulary about studying, exams, and personal skills.', 1, false);

insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Achieve', 'v', 'To succeed in doing something through effort or skill.', 'She achieved her goal after many years of practice.', 0 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Brain', 'n', 'The organ inside your head that controls thought, memory, and feeling.', 'Chess is good exercise for the brain.', 1 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Clever', 'adj', 'Quick to understand and learn things.', 'Rebecca is really clever. She always knows the answer.', 2 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Concentrate', 'v', 'To give all your attention to one thing.', 'It''s hard to concentrate with all this noise.', 3 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Consider', 'v', 'To think carefully about something, or to think of something as true.', 'Have you ever considered becoming a professional singer?', 4 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Course', 'n', 'A series of lessons on a particular subject.', 'She''s taking an English course this term.', 5 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Degree', 'n', 'A qualification given by a university after a course of study.', 'He has a degree in Chemistry.', 6 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Experience', 'n/v', 'Knowledge or skill gained from doing something.', 'She has a lot of experience in teaching.', 7 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Expert', 'n', 'Someone with special skill or knowledge in a subject.', 'Carl is a computer expert. Why don''t you ask him to fix your computer?', 8 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Fail', 'v', 'To not succeed in something, such as a test.', 'I hope I don''t fail the maths test tomorrow.', 9 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Guess', 'v', 'To give an answer without being sure if it''s correct.', 'I wasn''t sure of the answer so I guessed.', 10 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Hesitate', 'v', 'To pause or be unsure before doing something.', 'I always hesitate before making an important decision.', 11 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Instruction', 'n', 'Information that tells you how to do something.', 'Read the instructions before you start the test.', 12 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Make progress', 'phrase', 'To improve or move forward with something.', 'She''s making good progress in her studies.', 13 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Make sure', 'phrase', 'To check that something is true or has been done.', 'She told us to make sure we all understood.', 14 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Mark', 'n', 'A number or letter that shows how good your work is.', 'It''s nearly the end of term, so it will be your last mark.', 15 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Mental', 'adj', 'Relating to the mind.', 'He needs to do a mental calculation.', 16 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Pass', 'v', 'To succeed in a test or exam.', 'I hope you pass the exam tomorrow.', 17 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Qualification', 'n', 'A skill, type of experience, or exam result that makes you suitable for a job.', 'You need a teaching qualification for this job.', 18 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Remind', 'v', 'To help someone remember something.', 'Can you remind me to take this book back to the library?', 19 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Report', 'n/v', 'A written or spoken description of something that happened.', 'We have to write a subject report on what happened.', 20 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Revise', 'v', 'To study material again in order to prepare for an exam.', 'Can you revise enough before the exam?', 21 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Search', 'v', 'To look carefully in order to find something.', 'I searched everywhere for my keys.', 22 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Skill', 'n', 'The ability to do something well.', 'Speaking clearly is an important skill.', 23 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Smart', 'adj', 'Intelligent, able to think quickly.', 'Rosalind is a really smart, talented musician.', 24 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Subject', 'n', 'An area of knowledge studied at school.', 'Chemistry is my favourite subject.', 25 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Take an exam', 'phrase', 'To do a formal test of knowledge.', 'We had our English exam today.', 26 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Talented', 'adj', 'Having a natural ability to do something well.', 'Rosalind is a really talented musician.', 27 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Term', 'n', 'One of the periods a school year is divided into.', 'It''s nearly the end of term, so it will be the holidays soon.', 28 from public.discourses where slug = 'learning-and-doing';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Wonder', 'v', 'To want to know something, to think about something with curiosity.', 'I wonder how difficult the maths test tomorrow will be.', 29 from public.discourses where slug = 'learning-and-doing';

insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Cross out', 'Draw a line through something written.', 0 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Look up', 'Try to find information in a book, dictionary, etc.', 1 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Point out', 'Tell somebody an important piece of information.', 2 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Read out', 'Say something out loud while you are reading it.', 3 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Rip up', 'Tear something into pieces.', 4 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Rub out', 'Remove something written in pencil with a rubber.', 5 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Turn over', 'Turn something so the other side is facing you.', 6 from public.discourses where slug = 'learning-and-doing';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Write down', 'Write information on a piece of paper.', 7 from public.discourses where slug = 'learning-and-doing';

with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Begin', 0 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('began', 'verb (past)'), ('begun', 'verb (past participle)'), ('beginner', 'noun'), ('beginning', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Brave', 1 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('bravery', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Correct', 2 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('correction', 'noun'), ('incorrect', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Divide', 3 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('division', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Educate', 4 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('education', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Instruct', 5 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('instruction', 'noun'), ('instructor', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Memory', 6 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('memorise', 'verb'), ('memorial', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Refer', 7 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('reference', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Silent', 8 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('silence', 'noun'), ('silently', 'adverb')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Simple', 9 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('simplify', 'verb'), ('simplicity', 'noun')) as v(form, part_of_speech);

insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'ADJECTIVE', 'capable of', 'She''s capable of passing the exam easily.', 0 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'ADJECTIVE', 'talented at', 'He''s talented at music.', 1 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'chat about/in', 'We chatted about the exam in English.', 2 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'confuse sth with', 'Don''t confuse this word with that one.', 3 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'continue with', 'Let''s continue with the next question.', 4 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'cope with', 'It''s hard to cope with so much homework.', 5 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'help sb with', 'Can you help me with my English?', 6 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'know about', 'Do you know about dinosaurs?', 7 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'learn about', 'We''re learning about dinosaurs at school.', 8 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'succeed in', 'It''s a good idea to succeed in your exams.', 9 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'NOUN', 'an opinion about/of', 'What''s your opinion of the new teacher?', 10 from public.discourses where slug = 'learning-and-doing';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'NOUN', 'a question about', 'I have a question about the homework.', 11 from public.discourses where slug = 'learning-and-doing';

insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'by heart', 'Memorised completely.', 0 from public.discourses where slug = 'learning-and-doing';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'for instance', 'Used to give an example.', 1 from public.discourses where slug = 'learning-and-doing';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in conclusion', 'Used to introduce a final summary.', 2 from public.discourses where slug = 'learning-and-doing';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in fact', 'Used to emphasise that something is true.', 3 from public.discourses where slug = 'learning-and-doing';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in favour (of)', 'Supporting or agreeing with something.', 4 from public.discourses where slug = 'learning-and-doing';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in general', 'Considering something as a whole, not specific details.', 5 from public.discourses where slug = 'learning-and-doing';

with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'I ___ how difficult the maths test tomorrow will be.', 0 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('wonder', true), ('guess', false), ('hesitate', false), ('consider', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'It''s nearly the end of ___, so it will be the holidays soon!', 1 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('mark', false), ('course', false), ('term', true), ('degree', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Can you ___ me to take this book back to the library?', 2 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('revise', false), ('remind', true), ('report', false), ('search', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Carl is a computer ___. Why don''t you ask him to fix your computer?', 3 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('brain', false), ('expert', true), ('smart', false), ('talented', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Rebecca is really ___. She always knows the answer.', 4 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('mental', false), ('clever', true), ('hesitant', false), ('mark', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'I wasn''t sure of the answer so I ___.', 5 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('guessed', true), ('hesitated', false), ('considered', false), ('revised', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Have you ever ___ becoming a professional singer?', 6 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('guessed', false), ('hesitated', false), ('considered', true), ('achieved', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'PHRASAL_VERB', 'She ___ the instructions to make sure we all understood.', 7 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('read out', true), ('rubbed out', false), ('ripped up', false), ('pointed out', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'PHRASAL_VERB', 'We weren''t allowed to ___ anything written in pen.', 8 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('cross out', false), ('rub out', true), ('write down', false), ('turn over', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'PREPOSITIONAL_PHRASE', 'I learnt that poem ___ but I''ve forgotten it now.', 9 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('in fact', false), ('by heart', true), ('in general', false), ('for instance', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'WORD_PATTERN', 'It''s a good idea to do something active rather than ___ homework.', 10 from public.discourses where slug = 'learning-and-doing' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('cope with', true), ('chat about', false), ('help with', false), ('learn about', false)) as v(text, is_correct);


-- Buying and Selling
insert into public.discourses (slug, title, description, "order", coming_soon) values ('buying-and-selling', 'Buying and Selling', 'Vocabulary about shopping, money, and business.', 2, false);

insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Advertisement', 'n', 'A notice, picture, or film telling people about a product.', 'You''ve seen an advertisement offering a bargain.', 0 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Afford', 'v', 'To have enough money to pay for something.', 'Even good quality clothes are quite affordable in this shop.', 1 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Bargain', 'n/v', 'A thing bought cheaply, or an agreement about a price.', 'It was a real bargain at that price.', 2 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Brand', 'n', 'A type of product made by a particular company.', 'Which brand of trainers do you prefer?', 3 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Catalogue', 'n', 'A book or list of goods you can buy.', 'Look at the catalogue before you order.', 4 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Change', 'n/v', 'Money returned when you pay more than the price, or to exchange something.', 'Did you get your change from the shop?', 5 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Coin', 'n', 'A round piece of metal used as money.', 'Can I pay for this with coins?', 6 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Cost', 'n/v', 'The amount of money needed to buy something.', 'How much did the car cost?', 7 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Customer', 'n', 'A person who buys goods or services.', 'You need to know what your customers will demand.', 8 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Debt', 'n', 'Money that you owe to somebody.', 'Before borrowing from the bank, think about being in debt.', 9 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Demand', 'n/v', 'To ask for something firmly, or a strong need for a product.', 'You need to know what your customers will demand.', 10 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Export', 'n/v', 'To sell and send goods to another country.', 'Being big in business requires exports.', 11 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Fee', 'n', 'An amount of money paid for a service.', 'You have to pay a fee to join the club.', 12 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Fortune', 'n', 'A large amount of money.', 'Our course will help you make a fortune in business.', 13 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Import', 'n/v', 'To bring goods into a country in order to sell them.', 'The shop imports clothes from Italy.', 14 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Invest', 'v', 'To put money into something in order to make a profit.', 'Before borrowing money you have to decide whether to invest it.', 15 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Obtain', 'v', 'To get something.', 'You can obtain a discount if you pay in cash.', 16 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Owe', 'v', 'To need to pay money back to somebody.', 'He owes the bank a lot of money.', 17 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Property', 'n', 'A thing, or things, belonging to somebody; a building or land.', 'This shop''s property is worth a fortune.', 18 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Purchase', 'n/v', 'To buy something.', 'Could you help me make a decision about this purchase?', 19 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Receipt', 'n', 'A piece of paper showing you''ve paid for something.', 'Could you check your receipt before you leave?', 20 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Require', 'v', 'To need something.', 'Being big in business requires a certain way of thinking.', 21 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Sale', 'n', 'The act of selling, or a time when shops sell things cheaply.', 'Is the house next door up for sale?', 22 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Select', 'v', 'To choose something carefully.', 'You have to select the best option.', 23 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Supply', 'n/v', 'To provide something that is needed.', 'We''ll supply our customers with what they demand.', 24 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Variety', 'n', 'A number of different types of something.', 'Every supermarket sells a variety of good quality clothes.', 25 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Waste', 'n/v', 'To use something carelessly, without a good result.', 'Don''t waste your money on cheap products.', 26 from public.discourses where slug = 'buying-and-selling';
insert into public.vocabulary_words (discourse_id, word, word_class, meaning, example, "order") select id, 'Profit', 'n/v', 'Money gained in business after costs are paid.', 'Do you really make a profit again and again?', 27 from public.discourses where slug = 'buying-and-selling';

insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Add up', 'Find the total of something.', 0 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Come back (from)', 'Return (from somewhere).', 1 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Give away', 'Give something free of charge.', 2 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Hurry up', 'Do something more quickly.', 3 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Pay back', 'Return money (to somebody).', 4 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Save up (for)', 'Save money for a specific purpose.', 5 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Take back', 'Return something to the place it came from.', 6 from public.discourses where slug = 'buying-and-selling';
insert into public.phrasal_verbs (discourse_id, phrase, meaning, "order") select id, 'Take down', 'Remove something from a high place.', 7 from public.discourses where slug = 'buying-and-selling';

with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Add', 0 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('addition', 'noun'), ('additional', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Afford', 1 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('affordable', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Compare', 2 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('comparison', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Decide', 3 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('decision', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Expense', 4 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('expensive', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Judge', 5 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('judgment', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Serve', 6 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('service', 'noun'), ('servant', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'True', 7 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('truth', 'noun')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Use', 8 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('useful', 'adjective'), ('useless', 'adjective')) as v(form, part_of_speech);
with entry as (insert into public.word_formation_entries (discourse_id, base_word, "order") select id, 'Value', 9 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.word_formation_forms (entry_id, form, part_of_speech) select entry.id, v.form, v.part_of_speech from entry, (values ('valuable', 'adjective')) as v(form, part_of_speech);

insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'ADJECTIVE', 'wrong about', 'I was wrong about the price.', 0 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'belong to', 'This shop belongs to my uncle.', 1 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'borrow sth from sb', 'Can I borrow some money from you?', 2 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'buy sth from', 'I bought this jacket from that new shop.', 3 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'choose between sth/sth', 'It''s hard to choose between these two brands.', 4 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'compare sth to/with', 'Compare this price with the one online.', 5 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'decide on/whether/to', 'Have you decided on the vase yet?', 6 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'lend sth to sb', 'Could you lend some money to me?', 7 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'pay for sth', 'Can I pay for this with a credit card?', 8 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'VERB', 'spend sth on', 'Don''t spend too much money on clothes.', 9 from public.discourses where slug = 'buying-and-selling';
insert into public.word_patterns (discourse_id, category, pattern, meaning, "order") select id, 'NOUN', 'an advert(isement) for', 'I saw an advert for a big sale.', 10 from public.discourses where slug = 'buying-and-selling';

insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'by credit card/cheque', 'Paying using a credit card or cheque.', 0 from public.discourses where slug = 'buying-and-selling';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'for rent/discount', 'Available to rent, or with money off the price.', 1 from public.discourses where slug = 'buying-and-selling';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'for sale', 'Available to buy.', 2 from public.discourses where slug = 'buying-and-selling';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in cash', 'Paying with notes and coins.', 3 from public.discourses where slug = 'buying-and-selling';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in (good/bad) condition', 'Describing the physical state of something.', 4 from public.discourses where slug = 'buying-and-selling';
insert into public.prepositional_phrases (discourse_id, phrase, meaning, "order") select id, 'in debt', 'Owing money to somebody.', 5 from public.discourses where slug = 'buying-and-selling';

with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'So, you''ve seen an ___ for a bargain?', 0 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('advertisement', true), ('catalogue', false), ('receipt', false), ('property', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'But do you really know what you''re doing? Do you make a ___ again and again?', 1 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('cost', false), ('profit', true), ('debt', false), ('fee', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Why don''t you attend our specialist business seminar and learn how to make a ___ in business!', 2 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('catalogue', false), ('fortune', true), ('receipt', false), ('sale', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'Being big in business ___ a certain way of thinking.', 3 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('requires', true), ('imports', false), ('wastes', false), ('owes', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', 'You need to know what your customers will ___.', 4 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('waste', false), ('demand', true), ('select', false), ('export', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'TOPIC_VOCABULARY', '...and then find a way to ___ them with it at the right price.', 5 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('owe', false), ('supply', true), ('obtain', false), ('afford', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'WORD_FORMATION', 'Companies should always tell the ___ in advertisements.', 6 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('truth', true), ('true', false), ('truthful', false), ('truthfully', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'WORD_FORMATION', 'Could you help me make a ___ about this vase?', 7 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('decide', false), ('decision', true), ('decisive', false), ('decidable', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'WORD_FORMATION', 'Even good quality clothes are quite ___ in this shop.', 8 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('afford', false), ('affordable', true), ('affordability', false), ('affording', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'PHRASAL_VERB', 'She''s ___ for a new phone.', 9 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('saving up', true), ('paying back', false), ('giving away', false), ('taking down', false)) as v(text, is_correct);
with question as (insert into public.quiz_questions (discourse_id, category, prompt, "order") select id, 'PREPOSITIONAL_PHRASE', 'We need to pay ___ to get a discount.', 10 from public.discourses where slug = 'buying-and-selling' returning id)
insert into public.quiz_options (question_id, text, is_correct) select question.id, v.text, v.is_correct from question, (values ('in debt', false), ('in cash', true), ('for rent', false), ('for sale', false)) as v(text, is_correct);


-- Working and Business
insert into public.discourses (slug, title, description, "order", coming_soon) values ('working-and-business', 'Working and Business', 'Coming soon.', 3, true);


-- Community and Services
insert into public.discourses (slug, title, description, "order", coming_soon) values ('community-and-services', 'Community and Services', 'Coming soon.', 4, true);


-- Travel and Leisure
insert into public.discourses (slug, title, description, "order", coming_soon) values ('travel-and-leisure', 'Travel and Leisure', 'Coming soon.', 5, true);

